### ISSUE TITLE
Match predict workict doesn

### ISSUE THREAD

**Issue by jfjava2002** [minj/foxtrick#1379]
Hello,

I try to use the match predict function but it doesn't work. After clicking on the button, it displays the message "**_Object reference not set to an instance of an object_**."

```
Version 0.16.11.245 beta-7e28141 chrome, Sandboxed Chrome platform, fr locale, standard layout, LTR direction
 request time:  76  - init time:  19  ms
 not flipped
 page run time:  74  ms |  /Club/Matches/MatchOrder/ ?MatchID=561535897&SourceSystem=Hattrick&teamId=1759743
 interface ready:  true
 hasInterface
 ApiProxy: options:  {"cache_lifetime":"session"} cache_lifetime:  session  current timestamp:  Wed Feb 24 2016 10:33:00 GMT+0100 (Paris, Madrid)
 ApiProxy: use cached xml:  [["file","avatars"],["version","1.1"],["teamId",1759743]]
 hasAvatars
 ApiProxy: options:  {"cache_lifetime":"session"} cache_lifetime:  session  current timestamp:  Wed Feb 24 2016 10:33:00 GMT+0100 (Paris, Madrid)
 ApiProxy: use cached xml:  [["file","players"],["version","2.2"],["teamId",1759743],["includeMatchInfo","true"],["showLastMatch","true"]]
 Cannot read property 'textContent' of undefined
TypeError: Cannot read property 'textContent' of undefined
    at XMLDocument.xml.text (chrome-extension://bcbhbklnhonhojfmkobhhjkfaggkoali/content/util/api.js:220:15)
    at XMLDocument.xml.num (chrome-extension://bcbhbklnhonhojfmkobhhjkfaggkoali/content/util/api.js:239:20)
    at parseXml (chrome-extension://bcbhbklnhonhojfmkobhhjkfaggkoali/content/pages/players.js:307:28)
    at chrome-extension://bcbhbklnhonhojfmkobhhjkfaggkoali/content/pages/players.js:1057:7
    at chrome-extension://bcbhbklnhonhojfmkobhhjkfaggkoali/content/util/api.js:267:15
    at chrome-extension://bcbhbklnhonhojfmkobhhjkfaggkoali/content/util/api.js:352:6
    at chrome-extension://bcbhbklnhonhojfmkobhhjkfaggkoali/content/util/session-store.js:91:6
    at messageListener (extensions::messaging:346:9)
    at EventImpl.dispatchToListener (extensions::event_bindings:387:22)
    at Event.publicClass.(anonymous function) [as dispatchToListener] (extensions::utils:94:26)
 unable to retrieve player list.
 WARNING: inaccurate stamina prediction 6.94 7 "2016-02-06T20:00:00.000Z"
 WARNING: inaccurate stamina prediction 6.54 5 "2015-10-18T18:00:00.000Z"
 WARNING: inaccurate stamina prediction 5.51 4 "2015-09-26T19:00:00.000Z"
 ApiProxy: options:  {"cache_lifetime":"session"} cache_lifetime:  session  current timestamp:  Wed Feb 24 2016 10:33:00 GMT+0100 (Paris, Madrid)
 ApiProxy: use cached xml:  [["file","matchdetails"],["version","2.3"],["matchId",561535897],["sourceSystem","Hattrick"]]
 Object reference not set to an instance of an object.

```
I haven't found any topic related to this problem, I hope it will not be a doublon.

**Comment by jfjava2002** [comment]
After cleaning the cache, the function is now working. I can close the issue...

**Comment by minj** [comment]
Seems to have been a temporary CHPP glitch. Glad you overcame the issue yourself.
